#!/usr/bin/env python3
"""Pluribus — build orchestrator.

Two modes:

  --init    Scan the bitstream and write a TEMPLATE pins.tsv.
            The user then edits this file to add labels, functions, and
            confidence scores.  The template is a starting point — fill in
            what you know and leave the rest as defaults.

  (normal)  Run the full pipeline:
              Stage 1  load.py    — drop + reload netlist from bitstream
              Stage 2  reach.py   — parallel all-net BFS (NoGIL)
              Stage 3  (TODO)     — pattern detection
              Stage 4  (TODO)     — annotate from extra sources
              Stage 5  export     — write diff-friendly output TSV files

Usage
-----
  # First time — generate a template:
  ./fpga/pluribus/build.py --init \
    --config fpga/v7/FPGA_V07.bin.config \
    --out fpga/pluribus/hantek2d82-pins-template.tsv

  # Subsequent runs — full rebuild from annotated pin file:
  ./fpga/pluribus/build.py \
    --label V07 \
    --config fpga/v7/FPGA_V07.bin.config \
    --pins fpga/pluribus/aw2-pins.tsv

  # Every run CLEARS the database for this label and rebuilds from scratch.
  # Never use the database as a source of truth across runs — always rebuild.
"""

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

_HERE = Path(__file__).parent
_SCRIPTS = _HERE.parent / "scripts"
sys.path.insert(0, str(_SCRIPTS))
sys.path.insert(0, str(_HERE))

from db import engine, die, EFB_JF, JF_RE, BACKEND

TRELLIS_DBROOT = os.environ.get(
    "TRELLIS_DBROOT", "debris/tmp/prjtrellis/database"
)
TRELLIS_PYPATH = os.environ.get(
    "PYTHONPATH", "debris/tmp/prjtrellis/libtrellis/build"
)


# ── Stage: init — generate template TSV ──────────────────────────────────────

def cmd_init(config, out_path, device):
    """Scan bitstream and write a template pins.tsv."""
    from lifters import machxo2_lift as mx

    print(f"Scanning {config} for {device}…")
    lift   = mx.MachXO2Lift(device)
    pc     = lift.parse_config(config)
    design = lift.recover_netlist(pc)
    print(f"  {len(design.ffs)} FFs  {len(design.luts)} LUTs  {len(design.all_nets)} nets")

    # Build iomap from the recovered pinconn: tile → {pio: (direction, fabric_in, fabric_out)}
    # Pull from pc.tile_type and recovered pad nets
    # Find all PIO tiles and their directions
    lines = []
    lines.append(f"# Pluribus pin template — {os.path.basename(config)}")
    lines.append(f"# Generated by build.py --init  (EDIT THIS FILE — do not use as-is)")
    lines.append(f"#")
    lines.append(f"# device:  {device}")
    lines.append(f"# package: (fill in)")
    lines.append(f"# crystal: (fill in, e.g. 25MHz)")
    lines.append(f"# jtag:    (fill in, e.g. 'EFB only')")
    lines.append(f"#")
    lines.append(
        "# pin\trow\tcol\tpio\tdir\t\tlabel\t\tfunction\t\t\t\t\t\tconfidence"
    )
    lines.append("#")

    # EFB ports — auto-discovered
    lines.append("# ── EFB / SPI ────────────────────────────────────────────────────────────────")
    for (er,ec),t in pc.tile_type.items():
        if t != "CIB_CFG2": continue
        for (r,c,sink,src) in pc.arcs:
            if r != er or c != ec: continue
            m = JF_RE.match(src)
            if m:
                port = EFB_JF.get(int(m.group(1)), f"JF{m.group(1)}")
                net  = _resolve_net(design, lift, er, ec, sink)
                lines.append(f"# EFB {port} → net {net or '?'}")

    # Iterate the recovered pinconn TSV if it exists alongside config
    pinconn_tsv = Path(config).with_suffix(".config.iomap.tsv")
    if not pinconn_tsv.exists():
        pinconn_tsv = Path(str(config).replace(".bin.config", ".bin.config.iomap.tsv"))
    if pinconn_tsv.exists():
        lines.append("#")
        lines.append("# ── Fabric I/O pins (from iomap) ─────────────────────────────────────────────")
        with open(pinconn_tsv) as fh:
            for raw in fh:
                row_s = raw.strip()
                if not row_s or row_s.startswith("pin"):
                    continue
                parts = row_s.split("\t")
                if len(parts) < 7: continue
                pin, bank, d_raw, fn_raw, site, fab_in, fab_out = parts[:7]
                conn = parts[7] if len(parts) > 7 else ""
                if conn in ("spi_cfg", "pll", "unused"): continue
                if d_raw == "?": continue
                # parse site: "R{r}C{c}:{pio}"
                sm = re.match(r'R(\d+)C(\d+):PIO([A-D])', site)
                if not sm: continue
                sr, sc, spio = sm.group(1), sm.group(2), sm.group(3)
                d_str = d_raw.lower()
                if d_str not in ("in","out","inout"): continue
                d_out = "bidir" if d_str == "inout" else d_str
                fn_comment = fn_raw if fn_raw else ""
                lines.append(
                    f"{pin}\t{sr}\t{sc}\t{spio}\t{d_out}\t"
                    f"PIN{pin}\t(fill in: {fn_comment})\t1"
                )
    else:
        lines.append(f"# iomap TSV not found at {pinconn_tsv}")
        lines.append("# Run machxo2_lift.py to generate it, or fill in manually")

    out = "\n".join(lines) + "\n"
    with open(out_path, "w") as fh:
        fh.write(out)
    print(f"\nTemplate written to {out_path}")
    print("Edit this file: fill in labels, functions, and confidence scores (1-10)")
    print("Then run:  build.py --label V07 --config ... --pins <this-file>")


def _resolve_net(design, lift, row, col, wire):
    from lifters import machxo2_lift as mx
    key = lift.gkey(row, col, wire)
    if key is None or key not in design.dsu.p:
        return None
    return design.net_name.get(design.dsu.find(key))


# ── Stage: full pipeline ──────────────────────────────────────────────────────

def run_stage(name, cmd, env_extra=None, timings=None):
    """Run a subprocess stage; die hard on failure. Appends (name, elapsed) to timings."""
    env = dict(os.environ)
    if env_extra:
        env.update(env_extra)
    t = time.time()
    print(f"\n── {name} ──")
    r = subprocess.run(cmd, env=env)
    elapsed = time.time() - t
    if r.returncode != 0:
        die(f"Stage '{name}' failed (exit {r.returncode})")
    print(f"  {name} OK ({elapsed:.2f}s)")
    if timings is not None:
        timings.append((name, elapsed))


def reset_db():
    """Drop and recreate all tables. Called before every build."""
    import schema as _schema
    _schema.drop_all()
    _schema.init()
    print("DB reset: all tables dropped and recreated")


def cmd_annotate_only(label, pins, out_dir):
    """Re-import pin annotations and re-export without touching netlist or BFS.

    Requires a prior full build to have been run for this label.
    Clears only net_names (pins_tsv source), re-imports from the TSV, then
    re-exports all output TSVs.
    """
    from sqlalchemy import select, delete, insert, func
    import schema

    t0 = time.time()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with engine().connect() as conn:
        row = conn.execute(
            select(schema.bitstreams.c.id).where(schema.bitstreams.c.label == label)
        ).fetchone()
        if not row:
            die(f"Bitstream {label!r} not in DB — run a full build first")
        bs_id = row[0]

        # Verify netlist is present
        n_nets = conn.execute(
            select(func.count()).select_from(schema.nets).where(schema.nets.c.bitstream == bs_id)
        ).scalar()
        if n_nets == 0:
            die(f"Netlist for {label!r} is empty — run a full build first")

    with engine().begin() as conn:
        # Clear only pin-TSV-sourced annotations; keep any from other sources
        result = conn.execute(
            delete(schema.net_names).where(
                schema.net_names.c.bitstream == bs_id,
                schema.net_names.c.source == "pins_tsv",
            )
        )
        deleted = result.rowcount
        print(f"Cleared {deleted} net_names rows (source=pins_tsv) for {label!r}")

        # Re-parse pin TSV and re-insert annotations
        sys.path.insert(0, str(_HERE))
        from load import parse_pins_tsv
        meta, pin_rows = parse_pins_tsv(pins)
        print(f"  {len(pin_rows)} pins from {pins}")

        inserted = 0
        for pin, row_r, col, pio, direction, lbl, fn, conf in pin_rows:
            if direction in ("nc", "cfg"):
                continue
            # Look up net from pad_map
            pm = conn.execute(
                select(schema.pad_map.c.net_in, schema.pad_map.c.net_out).where(
                    schema.pad_map.c.bitstream == bs_id,
                    schema.pad_map.c.pin == pin,
                )
            ).fetchone()
            if pm is None:
                continue
            net_in, net_out = pm
            net = net_in or net_out
            if not net:
                continue
            confidence_str = "confirmed" if conf >= 8 else "estimate" if conf >= 5 else "guess"
            if BACKEND == "sqlite":
                stmt = insert(schema.net_names).prefix_with("OR IGNORE")
            else:
                from sqlalchemy.dialects.postgresql import insert as pg_insert
                stmt = pg_insert(schema.net_names).on_conflict_do_nothing()
            r2 = conn.execute(stmt.values(
                bitstream=bs_id,
                net=net,
                name=lbl,
                description=fn,
                confidence=confidence_str,
                source="pins_tsv",
            ))
            inserted += r2.rowcount

    print(f"  Inserted {inserted} net_names annotations")

    export_summary(label, out_dir)
    print(f"\n══ Annotate complete: {label}  ({time.time()-t0:.1f}s) ══")
    print(f"   Outputs in {out_dir}/")


def cmd_build(label, config, pins, device, package, out_dir, depth, workers):
    t0 = time.time()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    trellis_env = {
        "TRELLIS_DBROOT": TRELLIS_DBROOT,
        "PYTHONPATH":     TRELLIS_PYPATH,
    }

    timings = []

    # ── Reset DB before every build ───────────────────────────────────────
    t_reset = time.time()
    reset_db()
    timings.append(("reset_db", time.time() - t_reset))

    # ── Stage 1: load (needs pytrellis, always clears first) ──────────────
    run_stage("load", [
        sys.executable, str(_HERE / "load.py"),
        "--label",   label,
        "--config",  config,
        "--pins",    pins,
        "--device",  device,
        "--package", package,
    ], trellis_env, timings)

    # ── Stage 2: reach (NoGIL parallel BFS) ───────────────────────────────
    run_stage("reach", [
        "python3.14t", str(_HERE / "reach.py"),
        "--bitstream", label,
        "--depth",     str(depth),
        "--workers",   str(workers),
        "--replace",
    ], timings=timings)

    # ── Stage 2b: reach2 (reverse reach, FF cones, critical paths, dominators)
    run_stage("reach2", [
        sys.executable, str(_HERE / "reach2.py"),
        "--bitstream", label,
        "--workers",   str(workers),
    ], timings=timings)

    # ── Stage 2c: reach3 (symbolic expansion, clock crossings, const nets, etc.)
    run_stage("reach3", [
        sys.executable, str(_HERE / "reach3.py"),
        "--bitstream", label,
        "--workers",   str(workers),
        "--depth",     str(depth),
    ], timings=timings)

    # ── Stage 3: patterns (TODO — will be added) ──────────────────────────
    patterns_py = _HERE / "patterns.py"
    if patterns_py.exists():
        run_stage("patterns", [sys.executable, str(patterns_py), "--bitstream", label],
                  timings=timings)
    else:
        print("\n── patterns — SKIPPED (patterns.py not yet written) ──")

    # ── Stage 4: annotate from external sources (TODO) ────────────────────
    annotate_py = _HERE / "annotate.py"
    if annotate_py.exists():
        run_stage("annotate", [sys.executable, str(annotate_py), "--bitstream", label],
                  timings=timings)
    else:
        print("\n── annotate — SKIPPED (annotate.py not yet written) ──")

    # ── Stage 4b: reach4 — mechanical auto-naming ─────────────────────────
    run_stage("reach4", [
        sys.executable, str(_HERE / "reach4.py"),
        "--bitstream", label,
    ], timings=timings)

    # ── Stage 5: export diff-friendly output ──────────────────────────────
    t_exp = time.time()
    export_summary(label, out_dir)

    # Verilog emitter
    subprocess.run([
        sys.executable, str(_HERE / "verilog.py"),
        "--bitstream", label,
        "--out", str(Path(out_dir) / f"{label}.v"),
        "--top", label.lower().replace("-", "_"),
    ])

    # Human report
    subprocess.run([
        sys.executable, str(_HERE / "report.py"),
        "--bitstream", label,
        "--out", str(Path(out_dir) / f"{label}-report.txt"),
    ])

    timings.append(("export", time.time() - t_exp))

    # Resources report (issue #126) — runs after export, needs trellis env
    run_stage("report2", [
        sys.executable, str(_HERE / "report2.py"),
        "--bitstream", label,
        "--config",    config,
        "--out", str(Path(out_dir) / f"{label}-resources.txt"),
    ], trellis_env, timings)

    # Signal chain trace (issue #127)
    run_stage("chains", [
        sys.executable, str(_HERE / "chains.py"),
        "--bitstream", label,
        "--out", str(Path(out_dir) / f"{label}-chains.txt"),
    ], timings=timings)

    total = time.time() - t0
    print(f"\n══ Build complete: {label}  ({total:.2f}s total) ══")
    print(f"   Outputs in {out_dir}/")
    print(f"\n   Stage timings:")
    for stage, elapsed in timings:
        bar = "█" * int(elapsed / total * 30)
        print(f"   {stage:<12}  {elapsed:5.2f}s  {bar}")


# ── Stage 5: diff-friendly output ────────────────────────────────────────────

def export_summary(label, out_dir):
    """Write diff-friendly TSV summaries of the current DB state."""
    from sqlalchemy import select, func
    import schema

    with engine().connect() as conn:
        row = conn.execute(
            select(schema.bitstreams.c.id).where(schema.bitstreams.c.label == label)
        ).fetchone()
        if not row:
            die(f"Bitstream {label!r} not in DB after build — something went wrong")
        bs_id = row[0]

        print(f"\n── export ──")

        # ── pads summary ──
        f_pads = out_dir / f"{label}-pads.tsv"
        pm    = schema.pad_map
        nn_in  = schema.net_names.alias("nn_in")
        nn_out = schema.net_names.alias("nn_out")
        pads_q = (
            select(
                pm.c.pin,
                pm.c.label,
                pm.c.direction,
                pm.c.net_in,
                pm.c.net_out,
                nn_in.c.name.label("in_name"),
                nn_out.c.name.label("out_name"),
                nn_in.c.confidence,
                nn_in.c.description,
            )
            .select_from(
                pm
                .outerjoin(nn_in,  (nn_in.c.bitstream  == pm.c.bitstream) & (nn_in.c.net  == pm.c.net_in))
                .outerjoin(nn_out, (nn_out.c.bitstream == pm.c.bitstream) & (nn_out.c.net == pm.c.net_out))
            )
            .where(pm.c.bitstream == bs_id)
            .order_by(pm.c.pin)
        )
        with open(f_pads, "w") as fh:
            fh.write("pin\tlabel\tdir\tnet_in\tnet_out\tname\tconfidence\tdescription\n")
            for r in conn.execute(pads_q):
                pin, lbl, d, ni, no, nn_i, nn_o, conf, desc = r
                name = nn_i or nn_o or ""
                fh.write(f"{pin}\t{lbl}\t{d}\t{ni or ''}\t{no or ''}\t{name}\t{conf or ''}\t{desc or ''}\n")
        print(f"  {f_pads}")

        # ── EFB ports ──
        f_efb = out_dir / f"{label}-efb.tsv"
        ep = schema.efb_ports
        nn = schema.net_names
        efb_q = (
            select(
                ep.c.port_name,
                ep.c.net,
                nn.c.name,
                nn.c.description,
            )
            .select_from(
                ep.outerjoin(nn, (nn.c.bitstream == ep.c.bitstream) & (nn.c.net == ep.c.net))
            )
            .where(ep.c.bitstream == bs_id)
            .order_by(ep.c.port_name)
        )
        with open(f_efb, "w") as fh:
            fh.write("port\tnet\tname\tdescription\n")
            for r in conn.execute(efb_q):
                fh.write("\t".join(str(v or "") for v in r) + "\n")
        print(f"  {f_efb}")

        # ── clock domains ──
        f_clk = out_dir / f"{label}-clocks.tsv"
        cd  = schema.clock_domains
        nn2 = schema.net_names
        clk_q = (
            select(
                cd.c.clk_net,
                nn2.c.name,
                func.count().label("ff_count"),
            )
            .select_from(
                cd.outerjoin(nn2, (nn2.c.bitstream == cd.c.bitstream) & (nn2.c.net == cd.c.clk_net))
            )
            .where(cd.c.bitstream == bs_id)
            .group_by(cd.c.clk_net, nn2.c.name)
            .order_by(func.count().desc())
        )
        with open(f_clk, "w") as fh:
            fh.write("clk_net\tname\tff_count\n")
            for r in conn.execute(clk_q):
                fh.write("\t".join(str(v or "") for v in r) + "\n")
        print(f"  {f_clk}")

        # ── reachability summary (EFB → everything) ──
        f_reach = out_dir / f"{label}-reach-efb.tsv"
        ep2 = schema.efb_ports
        rch = schema.reachability
        nn3 = schema.net_names
        reach_q = (
            select(
                ep2.c.port_name,
                rch.c.dst,
                rch.c.min_hops,
                nn3.c.name,
            )
            .select_from(
                ep2
                .join(rch, (rch.c.bitstream == ep2.c.bitstream) & (rch.c.src == ep2.c.net))
                .outerjoin(nn3, (nn3.c.bitstream == rch.c.bitstream) & (nn3.c.net == rch.c.dst))
            )
            .where(ep2.c.bitstream == bs_id)
            .order_by(ep2.c.port_name, rch.c.min_hops, rch.c.dst)
        )
        with open(f_reach, "w") as fh:
            fh.write("efb_port\tdst_net\thops\tdst_name\n")
            for r in conn.execute(reach_q):
                fh.write("\t".join(str(v or "") for v in r) + "\n")
        print(f"  {f_reach}")

        # ── net stats ──
        f_stats = out_dir / f"{label}-stats.tsv"

        def _scalar(q):
            return str(conn.execute(q).scalar() or 0)

        bs_label_val = conn.execute(
            select(schema.bitstreams.c.label).where(schema.bitstreams.c.id == bs_id)
        ).scalar()

        stat_rows = [
            ("bitstream",     bs_label_val),
            ("ffs",           _scalar(select(func.count()).select_from(schema.ffs).where(schema.ffs.c.bitstream == bs_id))),
            ("luts",          _scalar(select(func.count()).select_from(schema.luts).where(schema.luts.c.bitstream == bs_id))),
            ("nets",          _scalar(select(func.count()).select_from(schema.nets).where(schema.nets.c.bitstream == bs_id))),
            ("fanout_edges",  _scalar(select(func.count()).select_from(schema.net_fanout).where(schema.net_fanout.c.bitstream == bs_id))),
            ("reach_pairs",   _scalar(select(func.count()).select_from(schema.reachability).where(schema.reachability.c.bitstream == bs_id))),
            ("named_nets",    _scalar(select(func.count()).select_from(schema.net_names).where(schema.net_names.c.bitstream == bs_id))),
            ("clock_domains", _scalar(select(func.count(schema.clock_domains.c.clk_net.distinct())).select_from(schema.clock_domains).where(schema.clock_domains.c.bitstream == bs_id))),
        ]
        with open(f_stats, "w") as fh:
            fh.write("metric\tvalue\n")
            for metric, value in stat_rows:
                fh.write(f"{metric}\t{value}\n")
        print(f"  {f_stats}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = ap.add_subparsers(dest="cmd")

    p_init = sub.add_parser("init", help="Generate a template pins.tsv from a bitstream")
    p_init.add_argument("--config",  required=True)
    p_init.add_argument("--out",     required=True, help="Output template TSV path")
    p_init.add_argument("--device",  default="LCMXO2-1200")

    p_build = sub.add_parser("build", help="Full rebuild pipeline (drops and recreates entire DB)")
    p_build.add_argument("--label",   required=True)
    p_build.add_argument("--config",  required=True)
    p_build.add_argument("--pins",    required=True)
    p_build.add_argument("--device",  default="LCMXO2-1200")
    p_build.add_argument("--package", default="TQFP100")
    p_build.add_argument("--out-dir", default="fpga/pluribus/out")
    p_build.add_argument("--depth",   type=int, default=8)
    p_build.add_argument("--workers", type=int, default=24)

    p_ann = sub.add_parser("annotate",
        help="Re-import pin annotations and re-export (no bitstream decode, no BFS)")
    p_ann.add_argument("--label",   required=True)
    p_ann.add_argument("--pins",    required=True)
    p_ann.add_argument("--out-dir", default="fpga/pluribus/out")

    args = ap.parse_args()

    if args.cmd == "init":
        from lifters import machxo2_lift  # validates pytrellis available before proceeding
        cmd_init(args.config, args.out, args.device)
    elif args.cmd == "build":
        cmd_build(args.label, args.config, args.pins,
                  args.device, args.package, args.out_dir,
                  args.depth, args.workers)
    elif args.cmd == "annotate":
        cmd_annotate_only(args.label, args.pins, args.out_dir)
    else:
        ap.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
