[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 1;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clko_w;
GLOBAL_PRIMARY_0_DRIVERTYPE = DCC;
GLOBAL_PRIMARY_0_LOADNUM = 1;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 0;
; I/O Bank 0 Usage
BANK_0_USED = 2;
BANK_0_AVAIL = 19;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 0;
BANK_1_AVAIL = 21;
BANK_1_VCCIO = NA;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 0;
BANK_2_AVAIL = 20;
BANK_2_VCCIO = NA;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 0;
BANK_3_AVAIL = 20;
BANK_3_VCCIO = NA;
BANK_3_VREF1 = NA;
