// Generated by gen_re_targets.py — known-ident SPI readback.
module fuzz (
    input  wire sck,
    input  wire cs_n,
    output wire miso
);
    localparam [63:0] IDENT = 64'hA5A5A5A5A5A5A5A5;
    reg [5:0] cnt;
    always @(posedge sck) begin
        if (cs_n) cnt <= 6'd0;
        else      cnt <= cnt + 1'b1;
    end
    assign miso = IDENT[6'd63 - cnt];
endmodule
