// Generated by gen_re_targets.py — JTAG-ER bridge coverage.
module fuzz (
    input  wire clk,
    output wire out0
);
    wire gnd = 1'b0;
    wire jce1_w, jshift_w, jupdate_w, jrstn_w, jtck_w, jtdi_w;
    JTAGF #(.ER1("ENABLED"), .ER2("ENABLED")) u0 (
        .TCK(), .TMS(), .TDI(), .JTDO1(gnd), .JTDO2(gnd),
        .TDO(), .JTCK(jtck_w), .JTDI(jtdi_w), .JSHIFT(jshift_w),
        .JUPDATE(jupdate_w), .JRSTN(jrstn_w),
        .JCE1(jce1_w), .JCE2(), .JRTI1(), .JRTI2()
    );
    reg out0_r;
    always @(posedge clk)
        out0_r <= jce1_w ^ jshift_w ^ jupdate_w ^ jrstn_w ^ jtck_w ^ jtdi_w;
    assign out0 = out0_r;
endmodule
