#!/usr/bin/env python3
"""Mechanically generate the RE-focused Diamond fuzz targets for the
soft-SPI / ident reverse-engineering (docs/diamond-re-oracle.md).

Emits standalone target dirs under diamond-fuzz/targets/, each with the
fuzz.v / fuzz.lpf / fuzz.ldf / run.tcl quartet that run_all_fuzz.py
auto-discovers (iterdir).  Rebuild them with:
    python3 diamond-fuzz/scripts/run_all_fuzz.py --targets 're_*' --no-pluribus -j 4

Two families:
  re_ident_<tag>   — strategy 2: a known 64-bit ident shifted onto miso by
                     a counter-indexed constant mux, on ordinary IO.  Varying
                     the ident value proves the readback encoding is robustly
                     recoverable regardless of the constant.
  re_cfgspi_<tag>  — strategy 1: the same shift-out but with SPI pins located
                     on the sysCONFIG slave-SPI sites and SLAVE_SPI_PORT
                     enabled, to expose the config-corner routing that the
                     OEM soft SPI decoder uses (pin 27 CSSPIN "fan=0 dead").
"""
import os
from pathlib import Path

TARGETS = Path(__file__).resolve().parents[1] / "targets"

LDF = '''<?xml version="1.0" encoding="UTF-8"?>
<BaliProject version="3.2" title="fuzz" device="LCMXO2-1200HC-5TG100C" default_implementation="impl1">
    <Options/>
    <Implementation title="impl1" dir="impl1" description="impl1" synthesis="lse" default_strategy="Strategy1">
        <Options/>
        <Source name="fuzz.v" type="Verilog" type_short="Verilog"><Options/></Source>
        <Source name="fuzz.lpf" type="Logic Preference" type_short="LPF"><Options/></Source>
    </Implementation>
    <Strategy name="Strategy1" file="../../aw21.sty"/>
</BaliProject>
'''

RUN_TCL = ('prj_project open "[file normalize [file join [file dirname [info script]] fuzz.ldf]]"\n'
           'prj_run PAR    -impl impl1\n'
           'prj_run Export -impl impl1 -task Bitgen\n'
           'prj_project close\n')

def verilog(ident_hex: str) -> str:
    return f'''// Generated by gen_re_targets.py — known-ident SPI readback.
module fuzz (
    input  wire sck,
    input  wire cs_n,
    output wire miso
);
    localparam [63:0] IDENT = 64'h{ident_hex};
    reg [5:0] cnt;
    always @(posedge sck) begin
        if (cs_n) cnt <= 6'd0;
        else      cnt <= cnt + 1'b1;
    end
    assign miso = IDENT[6'd63 - cnt];
endmodule
'''

def lpf(sites: dict, sysconfig: str | None) -> str:
    lines = ["BLOCK RESETPATHS;", "BLOCK ASYNCPATHS;", ""]
    for port, site in sites.items():
        lines += [f'LOCATE COMP "{port}" SITE "{site}";',
                  f'IOBUF PORT "{port}" IO_TYPE=LVCMOS33;', ""]
    lines.append('FREQUENCY PORT "sck" 100.000000 MHz;')
    if sysconfig:
        lines += ["", sysconfig]
    return "\n".join(lines) + "\n"

# Known-ident variants (ordinary IO on sites 88/87/84).
IDENTS = {
    "counting": "0123456789ABCDEF",
    "a5":       "A5A5A5A5A5A5A5A5",
    "ff00":     "FF00FF00FF00FF00",
    "adc":      "0200010913310785",   # the live V07 capture, as a control
}
IO_SITES = {"sck": "88", "cs_n": "87", "miso": "84"}

# Config-corner: SPI pins on the sysCONFIG slave-SPI sites, SLAVE_SPI enabled.
#   pin 31 = MCLK/SCK, 48 = SN/CS, 32 = SPISO/MISO  (per aw2-pins.tsv)
CFG_SITES = {"sck": "31", "cs_n": "48", "miso": "32"}
CFG_SYSCONFIG = "SYSCONFIG SLAVE_SPI_PORT=ENABLE ;"

def write_target(name: str, v_hex: str, sites: dict, sysconfig: str | None):
    d = TARGETS / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "fuzz.v").write_text(verilog(v_hex))
    (d / "fuzz.lpf").write_text(lpf(sites, sysconfig))
    (d / "fuzz.ldf").write_text(LDF)
    (d / "run.tcl").write_text(RUN_TCL)
    print(f"  wrote {name}")

# ── JTAG-ER family ──────────────────────────────────────────────────────────
# Exercises the JTAGF primitive's Extended-Register bridge (JTCK/JTDI/JSHIFT/
# JUPDATE/JRSTN → fabric).  These are the same signal names pluribus aliases
# onto the EFB JWBDATO wires; a JTAG-only design vs an EFB-WISHBONE design is
# the diff that disambiguates which function actually owns those wires.
JTAG_MODES = {
    "er1":    ('"ENABLED"', '"DISABLED"'),
    "er1er2": ('"ENABLED"', '"ENABLED"'),
}
def jtag_verilog(er1: str, er2: str) -> str:
    return f'''// Generated by gen_re_targets.py — JTAG-ER bridge coverage.
module fuzz (
    input  wire clk,
    output wire out0
);
    wire gnd = 1'b0;
    wire jce1_w, jshift_w, jupdate_w, jrstn_w, jtck_w, jtdi_w;
    JTAGF #(.ER1({er1}), .ER2({er2})) u0 (
        .TCK(), .TMS(), .TDI(), .JTDO1(gnd), .JTDO2(gnd),
        .TDO(), .JTCK(jtck_w), .JTDI(jtdi_w), .JSHIFT(jshift_w),
        .JUPDATE(jupdate_w), .JRSTN(jrstn_w),
        .JCE1(jce1_w), .JCE2(), .JRTI1(), .JRTI2()
    );
    reg out0_r;
    always @(posedge clk)
        out0_r <= jce1_w ^ jshift_w ^ jupdate_w ^ jrstn_w ^ jtck_w ^ jtdi_w;
    assign out0 = out0_r;
endmodule
'''

# ── Bottom-edge high-speed IO family ────────────────────────────────────────
# V07's OUTPUT_MIPI / OUTPUT_SSTL25_I on bottom-row pads write config into the
# un-fuzzed CIB F24–F27 frames (pluribus#29 item 3) — the same gap that leaves
# DAC_D0/D2/D6/D7 with no recoverable fabric driver.  Driving a bottom-edge pad
# with these standards is the fuzz that would name those bits.  (Some may fail
# to build without a bank VREF — a failure here still marks the gap.)
BOTTOM_IO = {
    "mipi":   "OUTPUT_MIPI",
    "sstl25": "SSTL25_I",
    "lvcmos25": "LVCMOS25",   # control: a standard that DOES decode
}
def bottomio_verilog() -> str:
    return '''// Generated by gen_re_targets.py — bottom-edge high-speed IO.
module fuzz (
    input  wire clk,
    output wire d0
);
    reg t;
    always @(posedge clk) t <= ~t;
    assign d0 = t;
endmodule
'''
def bottomio_lpf(iotype: str) -> str:
    # pin 36 = DAC_D0 (bottom row R11) per aw2-pins.tsv; pin 88 for clk.
    return ("BLOCK RESETPATHS;\nBLOCK ASYNCPATHS;\n\n"
            'LOCATE COMP "clk" SITE "88";\nIOBUF PORT "clk" IO_TYPE=LVCMOS33;\n\n'
            f'LOCATE COMP "d0" SITE "36";\nIOBUF PORT "d0" IO_TYPE={iotype};\n\n'
            'FREQUENCY PORT "clk" 100.000000 MHz;\n')

def write_raw(name: str, v: str, lpf_text: str):
    d = TARGETS / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "fuzz.v").write_text(v)
    (d / "fuzz.lpf").write_text(lpf_text)
    (d / "fuzz.ldf").write_text(LDF)
    (d / "run.tcl").write_text(RUN_TCL)
    print(f"  wrote {name}")

def main():
    print("generating RE fuzz targets:")
    for tag, hx in IDENTS.items():
        write_target(f"re_ident_{tag}", hx, IO_SITES, None)
    for tag, hx in IDENTS.items():
        write_target(f"re_cfgspi_{tag}", hx, CFG_SITES, CFG_SYSCONFIG)
    for tag, (er1, er2) in JTAG_MODES.items():
        write_raw(f"re_jtag_{tag}", jtag_verilog(er1, er2),
                  lpf({"clk": "88", "out0": "84"}, None))
    for tag, iotype in BOTTOM_IO.items():
        write_raw(f"re_bottomio_{tag}", bottomio_verilog(), bottomio_lpf(iotype))
    print("done. build with:  python3 diamond-fuzz/scripts/run_all_fuzz.py "
          "--targets 're_*' -j 4")

if __name__ == "__main__":
    main()
