#!/usr/bin/env python3.15t
"""Render the ECP5 corpus manifest + results as the committed Markdown table.

The corpus binaries are not in the repo (see .gitignore); this table IS the
deliverable.  It records, per bitstream: where it came from, its licence, the
part it targets, which toolchain built it, its SHA-256, and — separately — the
three claims the test harness distinguishes:

    decode   the native decoder parsed it
    oracle   that decode is line-identical to ecpunpack
    lift     the lifter produced a netlist that passes consistency checks

Usage:
    python3.15t scripts/ecp5_corpus_report.py [--results tmp/ecp5_corpus_results.json]
                                              [--out docs/ecp5-corpus.md]
"""
import argparse
import json
import os
import sys
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "corpus", "manifest.json")


def flow_of(rec):
    """Which toolchain built this file, read from the bitstream's ASCII header.

    Diamond writes 'Lattice Semiconductor Corporation Bitstream / Version:
    Diamond'; ecppack (prjtrellis) writes 'Part: LFE5U-...'.  Read the FILE
    where we have it rather than trusting the candidate-list notes: for the
    gzipped entries the header is inside the compressed stream, so the notes
    could only say 'gzip' and 23 files were left unattributed.  Evidence beats
    metadata, and the file is right there.
    """
    path = os.path.join(REPO, rec.get("local", ""))
    head = b""
    if os.path.exists(path):
        try:
            with open(path, "rb") as fh:
                if fh.read(2) == b"\x1f\x8b":
                    import gzip
                    with gzip.open(path, "rb") as gz:
                        head = gz.read(512)
                else:
                    fh.seek(0)
                    head = fh.read(512)
        except OSError:
            head = b""
    if b"Diamond" in head or b"Lattice Semiconductor Corporation" in head:
        return "Diamond"
    if b"Part:" in head:
        return "open (ecppack)"

    notes = (rec.get("notes") or "")
    if "flow=diamond" in notes.lower():
        return "Diamond"
    if "ecppack" in notes or "open-flow" in notes:
        return "open (ecppack)"
    return "?"


def short(s, n):
    s = s or ""
    return s if len(s) <= n else s[:n - 1] + "…"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results",
                    default=os.path.join(REPO, "tmp",
                                         "ecp5_corpus_results.json"))
    ap.add_argument("--diamond",
                    default=os.path.join(REPO, "tmp", "diamond_all.json"))
    ap.add_argument("--out", default=os.path.join(REPO, "docs",
                                                  "ecp5-corpus.md"))
    args = ap.parse_args()

    man = json.load(open(MANIFEST)) if os.path.exists(MANIFEST) else {"entries": []}
    by_local = {e["local"]: e for e in man["entries"]}

    results = json.load(open(args.results)) if os.path.exists(args.results) else []
    diamond = json.load(open(args.diamond)) if os.path.exists(args.diamond) else []

    L = []
    W = L.append
    W("# ECP5 real-world bitstream corpus")
    W("")
    W("Generated by `scripts/ecp5_corpus_report.py`. **Do not hand-edit.**")
    W("")
    W("## Why this corpus exists")
    W("")
    W("The ECP5 lifter was verified against 18 designs, and every one of them")
    W("was built by our own yosys + nextpnr + prjtrellis flow, with nextpnr's")
    W("placed netlist as the oracle. That is a closed loop: the same project")
    W("produced the bitstream, the reference netlist *and* the tile database,")
    W("so it cannot detect an assumption shared across all three.")
    W("")
    W("This corpus opens the loop. It is bitstreams **other people built**,")
    W("plus bitstreams **Lattice Diamond built** — a wholly independent")
    W("implementation of the same silicon.")
    W("")
    W("## The three claims, kept apart")
    W("")
    W("These are routinely conflated, and conflating them overstates what a")
    W("decoder has been shown to do. Reported separately throughout:")
    W("")
    W("| Claim | Meaning | Strength |")
    W("|---|---|---|")
    W("| **decode** | parsed to a `.config`, CRC verified, all frames consumed | weak on its own — a wrong geometry can still 'succeed' |")
    W("| **oracle** | that `.config` is line-identical to `ecpunpack` | strong — an independent implementation, works on any ECP5 file |")
    W("| **lift** | netlist recovered and self-consistent | weakest — without source, only consistency is checkable, not exactness |")
    W("")
    W("`ecpunpack` is the load-bearing oracle. Without a source netlist there")
    W("is nothing to check the *lift* against for exactness, so 'lifted' means")
    W("'structurally sane', never 'correct'.")
    W("")

    # ---- device identification note
    W("## Device identification")
    W("")
    W("The part is read from the bitstream's `VERIFY_ID` record and matched")
    W("against `devices.json`, **not** taken from the filename. Filenames in")
    W("this corpus are frequently wrong or absent, and decoding an 85F as a")
    W("12F does not fail loudly — it silently produces a plausible, wrong")
    W("fabric. The IDCODE is scanned before geometry is chosen.")
    W("")

    # ================= summary =================
    def summarise(rows, title):
        if not rows:
            return
        W(f"## {title}")
        W("")
        n = len(rows)
        dec = sum(1 for r in rows if r.get("decode") == "ok")
        orc = sum(1 for r in rows if r.get("oracle") == "identical")
        od = sum(1 for r in rows if r.get("oracle") == "DIFFERS")
        ou = sum(1 for r in rows if str(r.get("oracle", "")).startswith("unavailable"))
        lif = sum(1 for r in rows if r.get("lift") == "ok")
        notecp5 = sum(1 for r in rows
                      if str(r.get("decode", "")).startswith("not-ecp5"))
        unid = sum(1 for r in rows
                   if str(r.get("decode", "")).startswith("unidentified"))
        failed = sum(1 for r in rows
                     if str(r.get("decode", "")).startswith("raised"))
        W(f"- files: **{n}**")
        W(f"- identified as ECP5 and decoded: **{dec}**")
        if notecp5:
            W(f"- identified as another family (correctly rejected): {notecp5}")
        if unid:
            W(f"- unidentifiable (no sync word / no IDCODE): {unid}")
        if failed:
            W(f"- decode raised: **{failed}**")
        W(f"- **identical to `ecpunpack`: {orc}**"
          + (f" / {dec} decoded" if dec else ""))
        if od:
            W(f"- **DIFFER from `ecpunpack`: {od}**")
        if ou:
            W(f"- oracle unavailable (ecpunpack itself refused): {ou}")
        W(f"- lifted to a consistent netlist: **{lif}**")
        fused = sum(1 for r in rows
                    if r.get("metrics", {}).get("nets_multi_driver"))
        W(f"- netlists with a fused net (mis-connect): **{fused}**")
        drops = sum(1 for r in rows
                    if r.get("metrics", {}).get("lut_sites_missing"))
        W(f"- netlists with a dropped LUT site: **{drops}**")
        devs = Counter(r["device"] for r in rows if r.get("device"))
        W(f"- device spread: {', '.join(f'{k} ×{v}' for k, v in sorted(devs.items()))}")
        W("")

    summarise(diamond, "Results — Lattice Diamond builds (independent toolchain)")
    if diamond:
        W("These are ours, built with Diamond 3.14 rather than the open flow,")
        W("across three die sizes. They are the most informative entries in the")
        W("corpus: a different synthesiser, packer, router and bitgen produced")
        W("them, we know exactly what the source design is, and 45F/85F")
        W("geometry had never been exercised before this run.")
        W("")

    summarise(results, "Results — third-party bitstreams")

    # Split the third-party results by the toolchain that BUILT them.  This is
    # the comparison the corpus exists to make: the lifter was only ever tested
    # against open-flow output, so the Diamond column is the one carrying new
    # information.  A gap between the two columns would be the finding.
    if results:
        by_flow = {}
        for r in results:
            f = flow_of(by_local.get(r.get("local") or "", {}))
            by_flow.setdefault(f, []).append(r)
        W("### Third-party results split by originating toolchain")
        W("")
        W("The lifter had only ever seen open-flow (ecppack) output. The")
        W("Diamond column is where new information lives — a gap between the")
        W("two rows would itself be the finding.")
        W("")
        W("| Built by | files | decoded | identical to `ecpunpack` | lifted | fused nets |")
        W("|---|---|---|---|---|---|")
        for f, rows in sorted(by_flow.items()):
            dec = sum(1 for r in rows if r.get("decode") == "ok")
            orc = sum(1 for r in rows if r.get("oracle") == "identical")
            lif = sum(1 for r in rows if r.get("lift") == "ok")
            fus = sum(1 for r in rows
                      if r.get("metrics", {}).get("nets_multi_driver"))
            W(f"| {f} | {len(rows)} | {dec} | **{orc}** | {lif} | {fus} |")
        W("")

    # ================= gap exercise =================
    allr = [r for r in (results + diamond) if r.get("lift") == "ok"]
    if allr:
        W("## Which known gaps do real designs actually hit?")
        W("")
        W("The lifter has three documented gaps. All three **under-connect**")
        W("rather than mis-connect, which is the safe direction: a missing")
        W("edge is visible as an unconnected pin, a wrong edge is not. How")
        W("hard real designs lean on them:")
        W("")
        ccu2 = [r for r in allr if r.get("metrics", {}).get("lut_modes", {}).get("CCU2")]
        wm = [r for r in allr if (r.get("widemux_arcs") or 0) > 0]
        ck = [r for r in allr if r.get("metrics", {}).get("ff_clk_const")]
        W(f"- **CCU2 carry path** (FCI/FCO unmodelled): "
          f"exercised by **{len(ccu2)}/{len(allr)}** lifted designs")

        # Wide-mux usage is visible at DECODE time, so measure it over every
        # decoded file rather than only the lifted subset -- a much larger
        # denominator, and the lift stage is not needed to see it.
        dec_all = [r for r in (results + diamond) if r.get("decode") == "ok"]
        wm_dec = [r for r in dec_all if (r.get("widemux_arcs") or 0) > 0]
        wm_arcs = sum(r.get("widemux_arcs") or 0 for r in dec_all)
        W(f"- **Wide muxes** (F5MUX/PFUMX/L6MUX21): "
          f"exercised by **{len(wm_dec)}/{len(dec_all)}** *decoded* designs "
          f"({len(wm)}/{len(allr)} of the lifted subset), totalling "
          f"**{wm_arcs:,}** arcs into F5x/FXx pins. This is the most widely")
        W("  hit gap in the corpus by a wide margin — near-universal in real")
        W("  designs, and barely present in the 18 designs the lifter was")
        W("  originally verified against.")
        W(f"- **Clock globals** (prjtrellis parks non-TAP/SPINE globals at "
          f"(0,0), so the lifter drops them): "
          f"**{len(ck)}/{len(allr)}** designs have at least one FF whose "
          f"clock resolved to a constant")
        if ck:
            pcts = sorted(r["metrics"]["ff_clk_const_pct"] for r in ck)
            med = pcts[len(pcts) // 2]
            W("")
            W(f"  Share of FFs losing their clock, across the {len(ck)} affected")
            W(f"  designs: min {pcts[0]}%, **median {med}%**, max {pcts[-1]}%.")
            W("")
            W("  **This is the headline result of the corpus.** Our own test")
            W("  designs lose 0% — including the Diamond builds, which is why")
            W("  building more of them would never have surfaced this. Real")
            W("  designs lose roughly half their flip-flop clocks.")
            W("")
            W("  Root cause, confirmed by inspecting the decoded `.config`: the")
            W("  globals that get dropped are `G_DCS*` (dynamic clock select),")
            W("  `G_HPFE*`, and PLL outputs (`G_JLLCPLL*CLKO*`). Our test")
            W("  designs drive registers straight from a pad, so every global")
            W("  they use is `G_HPBX`/`G_VPTX` — the class prjtrellis *does*")
            W("  position. Any design with a PLL, which is essentially every")
            W("  real one, routes its main clock through the class it does not.")
            W("")
            W("  Worst-affected designs:")
            W("")
            for r in sorted(ck, key=lambda r: -r["metrics"]["ff_clk_const_pct"])[:5]:
                m = r["metrics"]
                W(f"  - `{short(r['label'], 44)}` — "
                  f"{m['ff_clk_const']}/{m['ffs']} FFs ({m['ff_clk_const_pct']}%)")
        W("")
        W("Note the direction of every one of these. A dropped clock leaves a")
        W("flip-flop with `clk=1'b0` — visibly wrong, and safe. It never")
        W("silently attaches the register to the *wrong* clock, which is what")
        W("unioning through a (0,0)-parked global would do. Across the whole")
        W("corpus the fused-net count is the number to watch, and it is zero.")
        W("")

    # ================= the table =================
    W("## Manifest")
    W("")
    W("Third-party binaries are **not** committed (`corpus/ecp5/` is")
    W("gitignored). This table plus `corpus/manifest.json` makes the corpus")
    W("reproducible from the original sources; the SHA-256 proves a refetch")
    W("got the same bytes that produced these results.")
    W("")
    W("| # | Project | Licence | Device | Flow | Size | SHA-256 (12) | decode | oracle | lift |")
    W("|---|---|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(sorted(results, key=lambda r: r.get("label", "")), 1):
        loc = r.get("local") or ""
        src = by_local.get(loc, {})
        sha = (r.get("sha256") or src.get("sha256") or "")[:12]
        size = r.get("bytes") or src.get("bytes") or 0
        dec = r.get("decode", "?")
        dec = "ok" if dec == "ok" else short(dec, 22)
        orc = r.get("oracle", "—")
        orc = {"identical": "**identical**", "DIFFERS": "**DIFFERS**"}.get(
            orc, short(str(orc), 18))
        lif = r.get("lift", "—")
        lif = "ok" if lif == "ok" else short(str(lif), 20)
        W(f"| {i} | {short(src.get('project') or r.get('project'), 30)} "
          f"| {short(src.get('license'), 14)} "
          f"| {r.get('device') or '—'} "
          f"| {flow_of(src)} "
          f"| {size // 1024} KB "
          f"| `{sha}` | {dec} | {orc} | {lif} |")
    W("")

    if diamond:
        W("### Diamond builds (ours — regenerable, not downloaded)")
        W("")
        W("Rebuild with `python3.15t scripts/ecp5_diamond_build.py "
          "--device <DEV>`.")
        W("")
        W("| Design | Device | Size | decode | oracle | lift | gaps exercised |")
        W("|---|---|---|---|---|---|---|")
        for r in sorted(diamond, key=lambda r: r.get("label", "")):
            m = r.get("metrics", {})
            gaps = []
            if m.get("lut_modes", {}).get("CCU2"):
                gaps.append(f"CCU2×{m['lut_modes']['CCU2']}")
            if r.get("widemux_arcs"):
                gaps.append(f"widemux×{r['widemux_arcs']}")
            if m.get("ff_clk_const"):
                gaps.append(f"clk-const×{m['ff_clk_const']}")
            orc = r.get("oracle", "—")
            orc = "**identical**" if orc == "identical" else short(str(orc), 18)
            W(f"| `{r.get('label')}` | {r.get('device') or '—'} "
              f"| {(r.get('bytes') or 0) // 1024} KB "
              f"| {r.get('decode')} | {orc} | {r.get('lift')} "
              f"| {', '.join(gaps) or '—'} |")
        W("")

    W("## Reproducing")
    W("")
    W("```")
    W("# 1. refetch the third-party corpus (writes corpus/manifest.json)")
    W("python3.15t scripts/ecp5_corpus_fetch.py --candidates tmp/corpus_github.json")
    W("# 2. confirm the bytes match what was tested")
    W("python3.15t scripts/ecp5_corpus_fetch.py --verify")
    W("# 3. build the Diamond half")
    W("python3.15t scripts/ecp5_diamond_build.py --device LFE5U-25F-6MG285I")
    W("# 4. run decode + oracle + lift over everything")
    W("#    Memory scales with --workers on the 85F lifts (8 concurrent 85F")
    W("#    lifts were measured at ~27 GB RSS).  Decode+oracle alone is cheap")
    W("#    and is also the strongest pair of claims, so --no-lift can run wide.")
    W("python3.15t scripts/ecp5_corpus_test.py --workers 12 --no-lift")
    W("python3.15t scripts/ecp5_corpus_test.py --workers 4")
    W("python3.15t scripts/ecp5_corpus_test.py --scan corpus/diamond --out tmp/diamond_all.json")
    W("# 5. regenerate this document")
    W("python3.15t scripts/ecp5_corpus_report.py")
    W("```")
    W("")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {args.out} ({len(L)} lines, "
          f"{len(results)} third-party + {len(diamond)} diamond)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
