#!/usr/bin/env python3
"""Generate a WISHBONE boot sequence for the recovered fabric from a board's
SPI register map.

The recovered netlist instantiates the EFB as a blackbox, so nothing drives the
fabric's control inputs and the datapath sits idle in simulation.  Swapping in
scripts/efb_open_model.v gives an open WISHBONE slave; this writes the register
sequence that configures it, straight from the board's own
`spi_registers.tsv` -- so the values in the sim are the values the firmware
actually uses, not invented ones.

It deliberately does NOT model the hardened-SPI serial front end.  Those pins are
wired to the EFB in silicon on MachXO2, never enter the fabric, and so are absent
from the bitstream; there is nothing to recover and inventing one would add
guesswork without adding evidence.  The bus writes are the same either way.

    python3 scripts/efb_boot_gen.py --board boards/<name> \
        [--out scripts/efb_wb_boot.vh]

Emits a Verilog include defining `EFB_BOOT_SEQUENCE`, a task body of
`efb_inst.wb_poke(addr, data);` calls.  Logs to ./tmp/logs/efb_boot_gen.log.
"""
import argparse
import csv
import logging
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LOG_DIR = REPO / "tmp/logs"

# Values a capture actually needs.  Sourced from the map's own descriptions:
# ARM_CAPTURE is documented "always 0x07 = ENABLE_ACQ | ARM_TRIGGER | RUN", the
# rest are ordinary mid-scale / free-running settings chosen so the fabric has
# a defined configuration rather than X.  Anything not listed is left at 0.
DEFAULTS = {
    "CH1_FRONTEND":  0x01,   # a range/coupling code; any defined value will do
    "CH2_FRONTEND":  0x01,
    "TRIG_MODE_AWG": 0x00,   # AWG off, auto trigger
    "TRIG_LEVEL_CH1": 0x80,  # mid-scale
    "TRIG_LEVEL_CH2": 0x80,
    "CH1_VOFFSET":   0x00,   # 0x8000 LE = 0 V, low byte first
    "CH2_VOFFSET":   0x00,
    "TIMEBASE_MODE": 0x00,
    "TIMEBASE_DIV":  0x00,   # divisor 0 -> full 250 MHz sample rate
    "TRIG_EDGE":     0x01,   # rising
    "ARM_CAPTURE":   0x07,   # documented constant: ENABLE_ACQ|ARM_TRIGGER|RUN
}


def setup_logging():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log = logging.getLogger("efb_boot_gen")
    if log.handlers:
        return log
    log.setLevel(logging.INFO)
    fmt = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    for h in (logging.StreamHandler(sys.stdout),
              logging.FileHandler(LOG_DIR / "efb_boot_gen.log")):
        h.setFormatter(fmt)
        log.addHandler(h)
    return log


def read_map(path):
    """(bank, addr, name, description) rows from a board spi_registers.tsv."""
    rows = []
    with open(path) as fh:
        for rec in csv.reader((l for l in fh if not l.startswith("#")),
                              delimiter="\t"):
            if len(rec) < 3 or rec[0] in ("bank", ""):
                continue
            try:
                addr = int(rec[1], 0)
            except ValueError:
                continue
            rows.append((rec[0], addr, rec[2], rec[3] if len(rec) > 3 else ""))
    return rows


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--board", required=True,
                    help="board directory holding spi_registers.tsv")
    ap.add_argument("--out", default=str(REPO / "scripts/efb_wb_boot.vh"))
    ap.add_argument("--inst", default="efb_inst",
                    help="EFB instance name in the recovered netlist")
    args = ap.parse_args()
    log = setup_logging()

    tsv = Path(args.board) / "spi_registers.tsv"
    if not tsv.is_file():
        sys.exit(f"no spi_registers.tsv under {args.board}")
    rows = read_map(tsv)
    log.info("%s: %d register rows", tsv, len(rows))

    lines = [
        "// GENERATED by scripts/efb_boot_gen.py -- do not edit.",
        f"// Source: {tsv.relative_to(REPO) if tsv.is_absolute() else tsv}",
        "//",
        "// WISHBONE register writes that configure the recovered fabric, using",
        "// the board's own firmware-confirmed values.  Applied via the open EFB",
        "// stand-in (scripts/efb_open_model.v); the hardened-SPI serial front",
        "// end is deliberately not modelled -- its pins never enter the fabric,",
        "// so the bitstream carries nothing about them.",
        "",
        "`define EFB_BOOT_SEQUENCE \\",
    ]
    emitted = 0
    body = []
    for bank, addr, name, _desc in rows:
        if bank == "READ":
            continue                      # readback registers, nothing to write
        if name not in DEFAULTS:
            continue
        body.append(f"    {args.inst}.wb_poke(8'h{addr:02x}, "
                    f"8'h{DEFAULTS[name]:02x});  /* {bank} {name} */")
        emitted += 1
    lines.append(" \\\n".join(body))
    lines.append("")
    Path(args.out).write_text("\n".join(lines) + "\n")
    log.info("wrote %s (%d writes; ARM_CAPTURE last)", args.out, emitted)
    for b in body:
        log.info("  %s", b.strip())
    return 0


if __name__ == "__main__":
    sys.exit(main())
